# Seek
RIGHT seek 5
LEFT seek -5

# Volume
UP add volume 5
DOWN add volume -5

# Playback
SPACE cycle pause
m cycle mute
f cycle fullscreen

# Subtitles
c cycle sub
[ add sub-pos -1
] add sub-pos +1

# Audio language
b cycle audio
