# General Settings
save-position-on-quit=yes               # Resume video where you left off
keep-open=yes                           # Don't close the player after video ends

# Video Profile & Quality
profile=high-quality                    # Built-in high quality preset
vo=gpu-next                             # Best video output driver
gpu-api=vulkan                          # Modern API (fallback to opengl if stuttering)

# Hardware Video Decoding (Fixes high CPU usage)
hwdec=auto-safe                         # Automatically choose safest hardware acceleration

# Audio and Subtitles
alang=eng,en                            # Priority audio languages
slang=eng,en,en-us,enus,en-sdh,sdh      # Target standard English, US English, and SDH variants
sub-auto=fuzzy                          # Autoload external subtitles containing the video title + 'eng' or 'sdh'
sub-forced-only=no                      # Ensure regular and SDH lines show up, not just forced signs/translations

# Screenshots
screenshot-format=png
screenshot-directory="~/Pictures/mpv"
